version: "3.9"

services:
  redis:
    image: "bitnami/redis:6.2.12"
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: "bitnami/postgresql:15.3.0"
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: "count"
      POSTGRESQL_USER: "count"
      POSTGRESQL_PASSWORD: "count"