version: "3.9"

services:

  webapp:
    image: "gridexx/counter-webapp:0.1.0"
    ports:
      - 3000:3000
    environment:
      - name=value

  ms:
    image: gridexx/counter-ms:0.1.0
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRESQL_HOST=postgres

  redis:
    image: "bitnami/redis:6.2.12"
    expose:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: "bitnami/postgresql:15.3.0"
    expose:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: "count"
      POSTGRESQL_USER: "count"
      POSTGRESQL_PASSWORD: "count"