version: "3.7"

volumes:
  postgres:

services:
  postgres:
    image: bitnami/postgresql:14.1.0-debian-10-r31
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres

  redis:
    image: bitnami/redis:7.0.9-debian-11-r5
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    image: ascoz/k8s-app:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  gateway:
    image: ascoz/k8s-gateway:latest
    depends_on:
      - app
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - APP_URL=http://app:3001
