
services:
    web:
        build: ./frontend
        ports:
          - 3001:3000
        networks:
          my-network:

    counter:
        image: docker.io/library/counter-service:0.0.1-SNAPSHOT
        ports:
          - 3002:3000
#        command:
        networks:
          my-network:

    redis:
        image: bitnami/redis:6.2.6-debian-10-r0
        restart: always
        networks:
          my-network:
        ports:
          - "6379:6379"
        volumes:
          - redis:/bitnami/redis/data

    postgres:
      image: bitnami/postgresql:14.1.0-debian-10-r31
      restart: always
      networks:
        - my-network
      ports:
        - "5432:5432"
      volumes:
        - postgres:/bitnami/postgresql
      environment:
        - POSTGRESQL_USER=postgres
        - POSTGRESQL_PASSWORD=postgres
        - POSTGRESQL_DATABASE=postgres

networks:
  my-network:

volumes:
  postgres:
  redis: