apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: esteban-baron
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx # estebanbaron/k8s-webapp
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: esteban-baron
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
