apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: esteban-baron
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: estebanbaron/k8s-webapp
          ports:
            - containerPort: 3000
          env:
            - name: API_BASE_URL
              value: http://api:3001
            - name: API_BASE_URL_BROWSER
              value: http://161.35.244.246:3001 # change with api service ip
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: esteban-baron
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
