apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: julien-dubois
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: redbeandock/do4-k8s-webapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: COUNTER_API_URL
          value: "http://counterapi"