apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: yann-pomie
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: woodenmaiden/counter-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      restartPolicy: Always
      