apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
data:
    username: {{ .Values.postgres.config.username }}
    database: {{ .Values.postgres.config.database }}
