apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: pizzolitto
spec:
  selector:
    app: database
  ports:
    # postgres
    - protocol: TCP
      port: 5432
      targetPort: 5432
