apiVersion: v1
kind: Service
metadata:
  name: ms-service
  namespace: pizzolitto
spec:
  selector:
    app: ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 6379
      targetPort: 6379
