apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-postgres-persistent-volume-claim
  namespace: alexis-bernard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
